"""Intent Resolution Runtime public M1 Intent IR surface."""

from .binding import (
    BindingAttribution,
    BindingAttribute,
    BindingAttributeKind,
    BindingConstraint,
    BindingConstraintOperator,
    BindingEvaluation,
    BindingInput,
    BindingInputRole,
    BindingIssue,
    BindingIssueKind,
    BindingRule,
    BindingSelectionMode,
    BindingSelectionPolicy,
    BoundValue,
    InterchangeableChoicePolicy,
    SymbolicReference,
    evaluate_binding,
)
from .context import (
    ClaimRecord,
    CompletenessRecord,
    ContextEnvelope,
    ContextReferenceRecord,
    EvidenceRecord,
    EvidenceRelation,
    EvidenceTargetKind,
    SourceAttribution,
    TemporalBasisKind,
    TemporalBasisRecord,
)
from .delegation import (
    DelegatedCapabilityAllowance,
    DelegatedContextReference,
    DelegatedScope,
    DelegatedWork,
    DelegatedWorkHandoff,
    DelegationConstraint,
    DelegationConstraintKind,
    DelegationHandoffAttribution,
    ExpectedDeliverable,
)
from .errors import IntentIRError, SerializationError, ValidationError
from .identity import RecordIdentity
from .intent import IntentExpression, IntentRequest, OriginAttribution, OriginKind, StableRef
from .resolution import (
    AssumptionKind,
    AssumptionRecord,
    CandidateAttribution,
    CandidateResolution,
    ClarificationNeed,
    ClarificationProposal,
    InformationNeed,
    InformationNeedProposal,
    ResolutionAttribution,
    ResolutionIssue,
    ResolutionIssueImpact,
    ResolutionIssueKind,
    ResolvedIntent,
)
from .worker_result import (
    WorkerNeed,
    WorkerNeedKind,
    WorkerResult,
    WorkerResultAttribution,
    WorkerResultMaterial,
    WorkerResultMaterialRole,
)
from .work import (
    WorkContinuationMode,
    WorkInput,
    WorkLiteralInput,
    WorkOutput,
    WorkPlan,
    WorkStep,
    WorkSymbolicInput,
)


def _seal_ir_type(base_type: type) -> None:
    base_name = base_type.__name__

    def _reject_subclassing(cls: type, **kwargs: object) -> None:
        raise TypeError(f"{base_name} is a closed IR type and cannot be subclassed")

    base_type.__init_subclass__ = classmethod(_reject_subclassing)


for _ir_type in (
    StableRef,
    OriginAttribution,
    IntentExpression,
    IntentRequest,
    RecordIdentity,
    SourceAttribution,
    ClaimRecord,
    EvidenceRecord,
    TemporalBasisRecord,
    CompletenessRecord,
    ContextReferenceRecord,
    ContextEnvelope,
    CandidateAttribution,
    ResolutionAttribution,
    AssumptionRecord,
    ResolutionIssue,
    ClarificationProposal,
    InformationNeedProposal,
    CandidateResolution,
    ResolvedIntent,
    ClarificationNeed,
    InformationNeed,
    BindingAttribute,
    BindingConstraint,
    BindingSelectionPolicy,
    BindingAttribution,
    SymbolicReference,
    BindingInput,
    BindingRule,
    BoundValue,
    BindingIssue,
    WorkLiteralInput,
    WorkSymbolicInput,
    WorkOutput,
    WorkStep,
    WorkPlan,
    DelegatedScope,
    DelegatedCapabilityAllowance,
    DelegatedContextReference,
    DelegationConstraint,
    ExpectedDeliverable,
    DelegatedWork,
    DelegationHandoffAttribution,
    DelegatedWorkHandoff,
    WorkerResultAttribution,
    WorkerResultMaterial,
    WorkerNeed,
    WorkerResult,
):
    _seal_ir_type(_ir_type)
del _ir_type, _seal_ir_type


__all__ = [
    "AssumptionKind",
    "AssumptionRecord",
    "BindingAttribution",
    "BindingAttribute",
    "BindingAttributeKind",
    "BindingConstraint",
    "BindingConstraintOperator",
    "BindingEvaluation",
    "BindingInput",
    "BindingInputRole",
    "BindingIssue",
    "BindingIssueKind",
    "BindingRule",
    "BindingSelectionMode",
    "BindingSelectionPolicy",
    "BoundValue",
    "CandidateAttribution",
    "CandidateResolution",
    "ClaimRecord",
    "ClarificationNeed",
    "ClarificationProposal",
    "CompletenessRecord",
    "ContextEnvelope",
    "ContextReferenceRecord",
    "DelegatedCapabilityAllowance",
    "DelegatedContextReference",
    "DelegatedScope",
    "DelegatedWork",
    "DelegatedWorkHandoff",
    "DelegationConstraint",
    "DelegationConstraintKind",
    "DelegationHandoffAttribution",
    "EvidenceRecord",
    "EvidenceRelation",
    "EvidenceTargetKind",
    "ExpectedDeliverable",
    "InformationNeed",
    "InformationNeedProposal",
    "IntentExpression",
    "IntentIRError",
    "IntentRequest",
    "InterchangeableChoicePolicy",
    "OriginAttribution",
    "OriginKind",
    "RecordIdentity",
    "ResolutionAttribution",
    "ResolutionIssue",
    "ResolutionIssueImpact",
    "ResolutionIssueKind",
    "ResolvedIntent",
    "SerializationError",
    "SourceAttribution",
    "StableRef",
    "SymbolicReference",
    "TemporalBasisKind",
    "TemporalBasisRecord",
    "ValidationError",
    "WorkerNeed",
    "WorkerNeedKind",
    "WorkerResult",
    "WorkerResultAttribution",
    "WorkerResultMaterial",
    "WorkerResultMaterialRole",
    "WorkContinuationMode",
    "WorkInput",
    "WorkLiteralInput",
    "WorkOutput",
    "WorkPlan",
    "WorkStep",
    "WorkSymbolicInput",
    "evaluate_binding",
]
